version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:AAaa123456@flynext-database.cv6qec6kk3sf.us-east-2.rds.amazonaws.com:5432/postgres
    command: npm run start



